// GENERATED by scripts/i18n-build.mjs from i18n/en/*.json.
// Do not edit; run `pnpm i18n:build`.

/** Every non-plural message key, mapped to its named substitutions. */
export interface MessageArgs {
  "actions_add_own_key_first": undefined;
  "actions_add_recipients_placeholder": undefined;
  "actions_age_cannot_sign": undefined;
  "actions_badge_you": undefined;
  "actions_clear_all_recipients": undefined;
  "actions_clear_input": undefined;
  "actions_copy_output": undefined;
  "actions_disabled_toast": { name: string | number; reason: string | number };
  "actions_download_output": undefined;
  "actions_encrypt_to_self_off": undefined;
  "actions_encrypt_to_self_on": undefined;
  "actions_find_replace": undefined;
  "actions_generate_key": undefined;
  "actions_go_to_keys": undefined;
  "actions_go_to_settings": undefined;
  "actions_go_to_workspace": undefined;
  "actions_group_contacts": undefined;
  "actions_group_keys": undefined;
  "actions_group_message": undefined;
  "actions_group_mode": undefined;
  "actions_group_my_keys": undefined;
  "actions_group_navigation": undefined;
  "actions_group_recent": undefined;
  "actions_group_result": undefined;
  "actions_group_session": undefined;
  "actions_group_settings": undefined;
  "actions_group_workspace": undefined;
  "actions_history": undefined;
  "actions_history_clear": undefined;
  "actions_history_delete_warning": undefined;
  "actions_history_empty": undefined;
  "actions_history_file_with_size": { name: string | number; size: string | number };
  "actions_history_metadata_only": undefined;
  "actions_history_no_content": undefined;
  "actions_history_no_matches": { query: string | number };
  "actions_history_off_never_cache": undefined;
  "actions_history_off_reason": undefined;
  "actions_history_op_signed": { op: string | number };
  "actions_history_open_entry": { title: string | number };
  "actions_history_recipient_with_id": { name: string | number; id: string | number };
  "actions_history_search_label": undefined;
  "actions_history_search_placeholder": undefined;
  "actions_history_to": { names: string | number };
  "actions_history_truncated": undefined;
  "actions_history_usage": { used: string | number; budget: string | number };
  "actions_history_when": { date: string | number; relative: string | number };
  "actions_import_key": undefined;
  "actions_keys_of_total": { active: string | number; count: string | number };
  "actions_language_last_used": { label: string | number };
  "actions_lock_now": undefined;
  "actions_mixed_engine_reason": undefined;
  "actions_need_recipient_or_password": undefined;
  "actions_no_input_decrypt": undefined;
  "actions_no_input_encrypt": undefined;
  "actions_no_input_sign": undefined;
  "actions_no_input_verify": undefined;
  "actions_no_keys_available": undefined;
  "actions_no_keys_found": undefined;
  "actions_no_matches": undefined;
  "actions_no_output_to_copy": undefined;
  "actions_nothing_to_clear": undefined;
  "actions_nothing_to_download": undefined;
  "actions_nothing_to_translate": undefined;
  "actions_open_history": undefined;
  "actions_open_security_presets": undefined;
  "actions_palette_label": undefined;
  "actions_palette_no_commands": undefined;
  "actions_palette_no_match": undefined;
  "actions_palette_placeholder": undefined;
  "actions_pick_language_placeholder": undefined;
  "actions_recipient_input_hint": undefined;
  "actions_remove_recipient": { name: string | number };
  "actions_remove_recipient_detail": { name: string | number; detail: string | number };
  "actions_reply_to_signer": undefined;
  "actions_run_mode": { mode: string | number };
  "actions_save_to_history_off": undefined;
  "actions_save_to_history_on": undefined;
  "actions_search_placeholder": undefined;
  "actions_select_key_placeholder": undefined;
  "actions_set_up": undefined;
  "actions_sign_when_encrypting_off": undefined;
  "actions_sign_when_encrypting_on": undefined;
  "actions_ssh_password_reason": undefined;
  "actions_style_bold": undefined;
  "actions_style_code": undefined;
  "actions_style_italic": undefined;
  "actions_style_strike": undefined;
  "actions_switch_to_workspace_first": undefined;
  "actions_toggle_recipient_list": undefined;
  "actions_translate_message": undefined;
  "actions_translate_result_to": { language: string | number };
  "actions_translate_to_title": undefined;
  "actions_translation_off": undefined;
  "app_action_title": undefined;
  "app_cmd_open": undefined;
  "app_cmd_open_decrypt": undefined;
  "app_cmd_open_encrypt": undefined;
  "app_cmd_open_sign": undefined;
  "app_cmd_open_verify": undefined;
  "app_copied": { label: string | number };
  "app_copied_wipe": { label: string | number; seconds: string | number };
  "app_copy_failed": undefined;
  "app_error_corrupted": undefined;
  "app_error_crx_unsigned": undefined;
  "app_error_key_expired": undefined;
  "app_error_key_locked": undefined;
  "app_error_key_not_found": undefined;
  "app_error_key_revoked": undefined;
  "app_error_no_decryption_key": undefined;
  "app_error_no_decryption_key_with_id": { key_id: string | number };
  "app_error_not_crx": undefined;
  "app_error_not_pgp_data": undefined;
  "app_error_ocb_unsupported": undefined;
  "app_error_passkey_dismissed": undefined;
  "app_error_passkey_failed": undefined;
  "app_error_password_required": undefined;
  "app_error_remedy_check_key": undefined;
  "app_error_remedy_import_key": undefined;
  "app_error_remedy_try_again": undefined;
  "app_error_storage_full": undefined;
  "app_error_symmetric_wrong_password": undefined;
  "app_error_tampered": undefined;
  "app_error_vault_locked": undefined;
  "app_error_weak_algorithm": undefined;
  "app_error_weak_password": undefined;
  "app_error_wrong_password": undefined;
  "app_menu_open_in_pgp_tools": undefined;
  "app_nav_label": undefined;
  "app_onboarding_advanced_options": undefined;
  "app_onboarding_algo_ecc_hint": undefined;
  "app_onboarding_algo_rsa_hint": undefined;
  "app_onboarding_algorithm_label": undefined;
  "app_onboarding_comment_label": undefined;
  "app_onboarding_comment_placeholder": undefined;
  "app_onboarding_create_key": undefined;
  "app_onboarding_create_passkey": undefined;
  "app_onboarding_email_label": undefined;
  "app_onboarding_email_placeholder": undefined;
  "app_onboarding_expiry_label": undefined;
  "app_onboarding_expiry_never": undefined;
  "app_onboarding_generate_failed": undefined;
  "app_onboarding_generating": undefined;
  "app_onboarding_identity_body": undefined;
  "app_onboarding_identity_title": undefined;
  "app_onboarding_intro_body": undefined;
  "app_onboarding_keep_defaults": undefined;
  "app_onboarding_name_label": undefined;
  "app_onboarding_name_placeholder": undefined;
  "app_onboarding_name_required": undefined;
  "app_onboarding_next": undefined;
  "app_onboarding_optional": undefined;
  "app_onboarding_passkey_prompt": undefined;
  "app_onboarding_preset_body": undefined;
  "app_onboarding_preset_title": undefined;
  "app_onboarding_prf_unsupported": undefined;
  "app_onboarding_protection_body": undefined;
  "app_onboarding_protection_title": undefined;
  "app_onboarding_rsa_slow": undefined;
  "app_onboarding_set_password": undefined;
  "app_onboarding_setup_failed": undefined;
  "app_onboarding_skip": undefined;
  "app_onboarding_storage_question": undefined;
  "app_onboarding_unlock_with_vault": undefined;
  "app_onboarding_unlock_with_vault_hint": undefined;
  "app_onboarding_use_preset": undefined;
  "app_oversized_more": { names: string | number; count: string | number };
  "app_tab_main": undefined;
  "app_vault_lock_retry": undefined;
  "app_vault_unreadable_body": undefined;
  "app_vault_unreadable_body_passkey": undefined;
  "app_vault_unreadable_title": undefined;
  "app_welcome_body": undefined;
  "app_welcome_credit_after": undefined;
  "app_welcome_credit_before": undefined;
  "app_welcome_open_failed": undefined;
  "app_welcome_opened": undefined;
  "app_welcome_start": undefined;
  "app_welcome_title": undefined;
  "common_back": undefined;
  "common_cancel": undefined;
  "common_continue": undefined;
  "common_copied": undefined;
  "common_copy": undefined;
  "common_decrypt": undefined;
  "common_delete": undefined;
  "common_done": undefined;
  "common_download": undefined;
  "common_encrypt": undefined;
  "common_keys": undefined;
  "common_lock": undefined;
  "common_off": undefined;
  "common_on": undefined;
  "common_private_key": undefined;
  "common_public_key": undefined;
  "common_remove": undefined;
  "common_save": undefined;
  "common_settings": undefined;
  "common_sign": undefined;
  "common_unlock": undefined;
  "common_verify": undefined;
  "extDescription": undefined;
  "extName": undefined;
  "import_action_import_contact": undefined;
  "import_action_replace_stored": undefined;
  "import_action_update_contact": undefined;
  "import_as_one_contact": undefined;
  "import_browse": undefined;
  "import_change_new_expiry": { date: string | number };
  "import_change_no_expiry": undefined;
  "import_change_reissued": undefined;
  "import_chip_crx": undefined;
  "import_chip_crx_title": undefined;
  "import_chip_pgp_private_title": undefined;
  "import_chip_pgp_public_title": undefined;
  "import_chip_ssh_private": undefined;
  "import_chip_ssh_private_title": undefined;
  "import_chip_ssh_public": undefined;
  "import_chip_ssh_public_title": undefined;
  "import_crx_headline": undefined;
  "import_crx_note": undefined;
  "import_default_pgp_name": undefined;
  "import_default_ssh_name": undefined;
  "import_drop_here": undefined;
  "import_dropzone_browse": undefined;
  "import_dropzone_text": undefined;
  "import_enter_passphrase": undefined;
  "import_failed": undefined;
  "import_github_fetched_note": { user: string | number };
  "import_github_invalid_username": undefined;
  "import_github_no_keys": { username: string | number };
  "import_github_none_usable": undefined;
  "import_github_not_found": { username: string | number };
  "import_github_offline": undefined;
  "import_github_omitted_reason": { max: string | number; count: string | number; username: string | number };
  "import_github_rate_limited": undefined;
  "import_github_server_error": undefined;
  "import_group_keys_chip_title": undefined;
  "import_group_label": undefined;
  "import_group_placeholder": undefined;
  "import_importing": undefined;
  "import_keyserver_invalid_query": undefined;
  "import_keyserver_multiple_keys": { host: string | number };
  "import_keyserver_not_a_key": { host: string | number };
  "import_keyserver_not_found_email": { host: string | number; subject: string | number };
  "import_keyserver_not_found_fingerprint": { host: string | number; subject: string | number };
  "import_keyserver_offline": { host: string | number };
  "import_keyserver_rate_limited": { host: string | number };
  "import_keyserver_server_error": { host: string | number };
  "import_label_field": undefined;
  "import_label_placeholder": undefined;
  "import_lookup_button": undefined;
  "import_lookup_failed": undefined;
  "import_lookup_invalid": undefined;
  "import_lookup_label": undefined;
  "import_lookup_placeholder": undefined;
  "import_no_key": undefined;
  "import_optional": undefined;
  "import_panel_aria_with_id": { keyid: string | number };
  "import_passphrase_label": undefined;
  "import_passphrase_placeholder": undefined;
  "import_paste_hint": undefined;
  "import_paste_label": undefined;
  "import_paste_placeholder": { shortcut: string | number };
  "import_private_unreadable": undefined;
  "import_reading": undefined;
  "import_reject_expired": { date: string | number };
  "import_reject_no_public_key": undefined;
  "import_reject_ssh_generic": undefined;
  "import_reject_unusable": undefined;
  "import_rejected_generic": undefined;
  "import_retry_minute": undefined;
  "import_reveal": undefined;
  "import_source_help": undefined;
  "import_ssh_headline": undefined;
  "import_ssh_private_headline": undefined;
  "import_ssh_private_note": undefined;
  "import_status_added_on": { date: string | number };
  "import_status_duplicate": undefined;
  "import_status_duplicate_added": { date: string | number };
  "import_status_update": undefined;
  "import_submit": undefined;
  "import_title": undefined;
  "import_title_update": undefined;
  "import_unknown_name": undefined;
  "import_unreadable": undefined;
  "import_worker_unreachable": undefined;
  "keygen_advanced_options": undefined;
  "keygen_algorithm_hint_ecc": undefined;
  "keygen_algorithm_hint_rsa": undefined;
  "keygen_algorithm_label": undefined;
  "keygen_comment_label": undefined;
  "keygen_comment_placeholder": undefined;
  "keygen_confirm_passphrase_placeholder": undefined;
  "keygen_confirm_password": undefined;
  "keygen_confirm_word": undefined;
  "keygen_copied_encrypted": undefined;
  "keygen_copied_plaintext": undefined;
  "keygen_create_heading": undefined;
  "keygen_create_subtitle_crx": undefined;
  "keygen_create_subtitle_pgp": undefined;
  "keygen_email_label": undefined;
  "keygen_email_placeholder": undefined;
  "keygen_encrypting": undefined;
  "keygen_error_expiry_past": undefined;
  "keygen_error_expiry_required": undefined;
  "keygen_error_generation_failed": undefined;
  "keygen_error_key_not_unlocked": undefined;
  "keygen_error_name_required": undefined;
  "keygen_error_passkey_failed": undefined;
  "keygen_error_passphrase_mismatch": undefined;
  "keygen_error_passphrase_short": undefined;
  "keygen_error_password_mismatch": undefined;
  "keygen_error_password_short": undefined;
  "keygen_error_prf_unsupported_authenticator": undefined;
  "keygen_error_wrong_password": undefined;
  "keygen_expires_on": { date: string | number };
  "keygen_expiry_1y": undefined;
  "keygen_expiry_2y": undefined;
  "keygen_expiry_3y": undefined;
  "keygen_expiry_custom": undefined;
  "keygen_expiry_heading": undefined;
  "keygen_expiry_label": undefined;
  "keygen_expiry_never": undefined;
  "keygen_expiry_subtitle": undefined;
  "keygen_export": undefined;
  "keygen_export_failed": undefined;
  "keygen_export_failed_detail": { message: string | number };
  "keygen_export_go_back_unlock": undefined;
  "keygen_export_nothing": undefined;
  "keygen_export_passphrase_intro": undefined;
  "keygen_export_plaintext_crx_left_out": undefined;
  "keygen_export_plaintext_warning_file": undefined;
  "keygen_export_skip_locked": undefined;
  "keygen_export_still_locked_after": undefined;
  "keygen_export_summary": { ext: string | number; private_keys: string | number; private_block: string | number; contacts: string | number; public_block: string | number };
  "keygen_export_title": undefined;
  "keygen_export_unlock_intro": undefined;
  "keygen_export_with_passphrase": undefined;
  "keygen_export_without_passphrase": undefined;
  "keygen_exporter_crx_encrypted_blurb": undefined;
  "keygen_exporter_crx_encrypted_button": undefined;
  "keygen_exporter_crx_plaintext_blurb": undefined;
  "keygen_exporter_crx_plaintext_button": undefined;
  "keygen_exporter_crx_title": undefined;
  "keygen_exporter_crx_unlock_passkey": undefined;
  "keygen_exporter_crx_unlock_password": undefined;
  "keygen_exporter_pgp_encrypted_blurb": undefined;
  "keygen_exporter_pgp_plaintext_blurb": undefined;
  "keygen_exporter_pgp_title": undefined;
  "keygen_exporting": undefined;
  "keygen_generating_key": undefined;
  "keygen_generating_passkey": undefined;
  "keygen_generating_rsa_hint": undefined;
  "keygen_key_password_placeholder": undefined;
  "keygen_key_size_4096": undefined;
  "keygen_key_size_label": undefined;
  "keygen_label_label": undefined;
  "keygen_label_placeholder": undefined;
  "keygen_name_label": undefined;
  "keygen_name_placeholder": undefined;
  "keygen_next": undefined;
  "keygen_optional": undefined;
  "keygen_passkey_default_user": undefined;
  "keygen_passkey_imported_user": undefined;
  "keygen_passphrase_placeholder": undefined;
  "keygen_password_placeholder": undefined;
  "keygen_prf_unsupported_chrome": undefined;
  "keygen_prf_unsupported_intro": undefined;
  "keygen_prf_unsupported_mac": undefined;
  "keygen_prf_unsupported_windows": undefined;
  "keygen_protect_heading": undefined;
  "keygen_protect_subtitle": undefined;
  "keygen_protection_intro": undefined;
  "keygen_protection_passkey": undefined;
  "keygen_protection_passkey_desc": undefined;
  "keygen_protection_passkey_unavailable": undefined;
  "keygen_protection_password": undefined;
  "keygen_protection_password_desc": undefined;
  "keygen_protection_recommended": undefined;
  "keygen_protection_reuse_passkey": undefined;
  "keygen_submit_create_passkey": undefined;
  "keygen_submit_generate": undefined;
  "keygen_submit_use_passkey": undefined;
  "keygen_title": undefined;
  "keygen_type_crx": undefined;
  "keygen_type_pgp": undefined;
  "keygen_type_to_confirm_after": undefined;
  "keygen_type_to_confirm_before": undefined;
  "keygen_unlock_gate_passkey": undefined;
  "keygen_unlock_gate_password": undefined;
  "keygen_unlocking": undefined;
  "keys_also_known_as": undefined;
  "keys_banner_encrypt_only_contact": undefined;
  "keys_banner_encrypt_only_own": undefined;
  "keys_banner_expired_contact": undefined;
  "keys_banner_expired_on": { date: string | number };
  "keys_banner_expired_own": undefined;
  "keys_banner_expired_title": { when: string | number };
  "keys_banner_expires_soon": undefined;
  "keys_banner_no_reason": undefined;
  "keys_banner_revoked_contact": undefined;
  "keys_banner_revoked_own": undefined;
  "keys_banner_revoked_title": undefined;
  "keys_banner_sign_only_contact": undefined;
  "keys_banner_sign_only_own": undefined;
  "keys_banner_unusable_body": undefined;
  "keys_banner_unusable_title": undefined;
  "keys_bits": { bits: string | number };
  "keys_bulk_delete_contacts_body": undefined;
  "keys_bulk_delete_private_body": undefined;
  "keys_bulk_delete_title": undefined;
  "keys_cancel_selection_aria": undefined;
  "keys_cap_auth": undefined;
  "keys_cap_certify": undefined;
  "keys_cap_encrypt": undefined;
  "keys_cap_sign": undefined;
  "keys_chip_contact": undefined;
  "keys_chip_contact_title": undefined;
  "keys_chip_protection_title": undefined;
  "keys_chip_your_key": undefined;
  "keys_chip_your_key_title": undefined;
  "keys_confirm_delete_key_title": undefined;
  "keys_confirm_remove_contact_title": undefined;
  "keys_contact_expired": { date: string | number };
  "keys_contact_expired_title": { date: string | number };
  "keys_contact_expires": { date: string | number };
  "keys_contact_keys_all_title": undefined;
  "keys_contact_keys_partial": { active: string | number; total: string | number };
  "keys_contact_keys_partial_title": { active: string | number; total: string | number };
  "keys_contact_options_aria": undefined;
  "keys_contacts_heading": undefined;
  "keys_contacts_heading_count": { count: string | number };
  "keys_contacts_heading_encrypted": undefined;
  "keys_contacts_locked": undefined;
  "keys_copy_fingerprint_aria": undefined;
  "keys_copy_private_key": undefined;
  "keys_copy_public_key": undefined;
  "keys_default_badge": undefined;
  "keys_default_removed": undefined;
  "keys_default_set": undefined;
  "keys_default_title": undefined;
  "keys_delete_crx_body": undefined;
  "keys_delete_key": undefined;
  "keys_delete_key_body": undefined;
  "keys_delete_key_permanently": undefined;
  "keys_deselect_all": undefined;
  "keys_details_aria": { name: string | number };
  "keys_download_public_key": undefined;
  "keys_empty": undefined;
  "keys_encrypt_to": undefined;
  "keys_enter_password_placeholder": undefined;
  "keys_expires_value": { date: string | number; when: string | number };
  "keys_export": undefined;
  "keys_fact_added": undefined;
  "keys_fact_algorithm": undefined;
  "keys_fact_created": undefined;
  "keys_fact_expires": undefined;
  "keys_fact_fingerprint": undefined;
  "keys_fact_last_used": undefined;
  "keys_fact_used_for": undefined;
  "keys_generate_button": undefined;
  "keys_group_row_label": undefined;
  "keys_import_button": undefined;
  "keys_key_details": undefined;
  "keys_key_options_aria": undefined;
  "keys_loading": undefined;
  "keys_my_keys_heading": undefined;
  "keys_never": undefined;
  "keys_no_contacts_match": { query: string | number };
  "keys_no_subkeys": undefined;
  "keys_parse_failed": undefined;
  "keys_passkey_failed": undefined;
  "keys_protection_passkey": undefined;
  "keys_protection_password": undefined;
  "keys_public_key_copied": undefined;
  "keys_recipient_disable_title": undefined;
  "keys_recipient_dont_use": undefined;
  "keys_recipient_enable_title": undefined;
  "keys_recipient_last_active_title": undefined;
  "keys_recipient_not_used": undefined;
  "keys_recipient_off_title": undefined;
  "keys_recipient_use": undefined;
  "keys_remove_contact": undefined;
  "keys_remove_contact_body": undefined;
  "keys_remove_default": undefined;
  "keys_rename": undefined;
  "keys_rename_contact_title": undefined;
  "keys_rename_crx_title": undefined;
  "keys_rename_field_label": undefined;
  "keys_rename_hint": { identity: string | number };
  "keys_rename_key_title": undefined;
  "keys_rename_placeholder_contact": undefined;
  "keys_rename_placeholder_crx": undefined;
  "keys_rename_placeholder_key": undefined;
  "keys_reselect": undefined;
  "keys_revocation_certificate": undefined;
  "keys_revocation_create": undefined;
  "keys_revocation_create_failed": undefined;
  "keys_revocation_created": undefined;
  "keys_revocation_creating": undefined;
  "keys_revocation_have_body": undefined;
  "keys_revocation_missing_body": undefined;
  "keys_revocation_unlock_first": undefined;
  "keys_revoked_reason": { reason: string | number };
  "keys_row_created": { date: string | number };
  "keys_row_expired": { date: string | number };
  "keys_row_expires": { date: string | number };
  "keys_row_never_expires": undefined;
  "keys_save_failed": undefined;
  "keys_search_contacts_placeholder": undefined;
  "keys_select": undefined;
  "keys_select_all": undefined;
  "keys_selection_actions_aria": undefined;
  "keys_set_default": undefined;
  "keys_size_bytes": { size: string | number };
  "keys_size_kb": { size: string | number };
  "keys_size_mb": { size: string | number };
  "keys_source_github": { user: string | number };
  "keys_source_keyserver": { user: string | number };
  "keys_ssh_chip_title": undefined;
  "keys_status_expired": undefined;
  "keys_status_invalid": undefined;
  "keys_status_locked": undefined;
  "keys_status_revoked": undefined;
  "keys_status_sealed": undefined;
  "keys_status_unlocked": undefined;
  "keys_subkey_label": undefined;
  "keys_subkeys_title": undefined;
  "keys_subkeys_truncated": { count: string | number };
  "keys_undo": undefined;
  "keys_unknown_name": undefined;
  "keys_weak_sha1": undefined;
  "keys_wrong_password": undefined;
  "settings_crx_default_key_name": undefined;
  "settings_crx_info_get_body": { crx: string | number; load_unpacked: string | number };
  "settings_crx_info_get_title": undefined;
  "settings_crx_info_how_title": undefined;
  "settings_crx_info_ladder_ci": { term: string | number };
  "settings_crx_info_ladder_ci_term": undefined;
  "settings_crx_info_ladder_hardware": { term: string | number };
  "settings_crx_info_ladder_hardware_term": undefined;
  "settings_crx_info_ladder_title": undefined;
  "settings_crx_info_ladder_vault": { term: string | number };
  "settings_crx_info_ladder_vault_term": undefined;
  "settings_crx_info_link": undefined;
  "settings_crx_info_not_pgp_body": { crx: string | number };
  "settings_crx_info_not_pgp_title": undefined;
  "settings_crx_info_pitch_p1": undefined;
  "settings_crx_info_pitch_p2": undefined;
  "settings_crx_info_pitch_title": undefined;
  "settings_crx_info_step_1": undefined;
  "settings_crx_info_step_2": { public: string | number; path: string | number };
  "settings_crx_info_step_3": { zip: string | number; save: string | number; crx: string | number };
  "settings_crx_info_step_4": { crx: string | number };
  "settings_crx_info_term_dashboard_path": undefined;
  "settings_crx_info_term_load_unpacked": undefined;
  "settings_crx_info_term_public": undefined;
  "settings_crx_info_title": undefined;
  "settings_import_browse": undefined;
  "settings_import_crx_failure_detail": { name: string | number; error: string | number };
  "settings_import_default_user_id": undefined;
  "settings_import_failed": undefined;
  "settings_import_failed_named": { name: string | number; error: string | number };
  "settings_import_importing": undefined;
  "settings_import_keys_title": undefined;
  "settings_import_next": undefined;
  "settings_import_no_keys": undefined;
  "settings_import_passkey_name": undefined;
  "settings_import_passphrase_placeholder": undefined;
  "settings_import_paste_intro": undefined;
  "settings_import_paste_placeholder": undefined;
  "settings_import_prf_unsupported": undefined;
  "settings_import_unknown_error": undefined;
  "settings_preset_apply": undefined;
  "settings_preset_apply_delete_history": undefined;
  "settings_preset_applying": undefined;
  "settings_preset_confirm_history": { size: string | number };
  "settings_preset_confirm_replace": { preset: string | number };
  "settings_preset_custom_name": undefined;
  "settings_preset_custom_notice": { custom: string | number };
  "settings_preset_intro": undefined;
  "settings_preset_keep_custom": undefined;
  "settings_preset_replace_custom": undefined;
  "settings_preset_title": undefined;
  "settings_shortcuts_copy_output": undefined;
  "settings_shortcuts_download_output": undefined;
  "settings_shortcuts_find_replace": undefined;
  "settings_shortcuts_global_note": { url: string | number };
  "settings_shortcuts_group_global": undefined;
  "settings_shortcuts_group_message": undefined;
  "settings_shortcuts_group_modes": undefined;
  "settings_shortcuts_group_palette": undefined;
  "settings_shortcuts_group_workspace": undefined;
  "settings_shortcuts_manage": undefined;
  "settings_shortcuts_open_app": undefined;
  "settings_shortcuts_open_in_mode": { mode: string | number };
  "settings_shortcuts_open_palette": undefined;
  "settings_shortcuts_open_palette_note": undefined;
  "settings_shortcuts_pick_recipient": undefined;
  "settings_shortcuts_pick_recipient_note": undefined;
  "settings_shortcuts_remove_recipient": undefined;
  "settings_shortcuts_remove_recipient_note": undefined;
  "settings_shortcuts_reply": undefined;
  "settings_shortcuts_run_mode": undefined;
  "settings_shortcuts_style_note": undefined;
  "settings_shortcuts_switch_mode": { mode: string | number };
  "settings_shortcuts_title": undefined;
  "settings_shortcuts_unbound": undefined;
  "settings_shortcuts_unbound_note": undefined;
  "settings_translation_detector": undefined;
  "settings_translation_download_failed": undefined;
  "settings_translation_enable": undefined;
  "settings_translation_enable_desc": undefined;
  "settings_translation_failed": undefined;
  "settings_translation_pack_gone": undefined;
  "settings_translation_pack_not_offered": undefined;
  "settings_translation_pack_pair": { from: string | number; to: string | number };
  "settings_translation_pack_progress": { percent: string | number };
  "settings_translation_pack_ready": undefined;
  "settings_translation_packs": undefined;
  "settings_translation_packs_desc": { size: string | number };
  "settings_translation_target": undefined;
  "settings_translation_title": undefined;
  "settings_translation_unavailable_device": undefined;
  "settings_translation_unsupported": undefined;
  "shared_about": undefined;
  "shared_about_extensions": undefined;
  "shared_advanced_mode": undefined;
  "shared_advanced_mode_desc": undefined;
  "shared_auto_download_files_desc": undefined;
  "shared_auto_download_files_title": undefined;
  "shared_auto_download_text_desc": undefined;
  "shared_auto_download_text_title": undefined;
  "shared_auto_lock_desc": undefined;
  "shared_auto_lock_title": undefined;
  "shared_backup": undefined;
  "shared_backup_desc": undefined;
  "shared_bundle_auto_lock": { duration: string | number };
  "shared_bundle_auto_lock_off": undefined;
  "shared_bundle_auto_lock_tabs": { duration: string | number };
  "shared_bundle_discovery_off": undefined;
  "shared_bundle_discovery_on": undefined;
  "shared_bundle_history_off": undefined;
  "shared_bundle_history_on": undefined;
  "shared_bundle_never_cache_off": undefined;
  "shared_bundle_never_cache_on": undefined;
  "shared_bundle_no_encrypt_to_self": undefined;
  "shared_bundle_storage_local": undefined;
  "shared_bundle_storage_sync": undefined;
  "shared_bundle_unlock_on_open_off": undefined;
  "shared_bundle_unlock_on_open_on": undefined;
  "shared_byline_before": undefined;
  "shared_check_extensions": undefined;
  "shared_clear_name": undefined;
  "shared_commands": undefined;
  "shared_confirm_type_after": undefined;
  "shared_confirm_type_aria": { text: string | number };
  "shared_confirm_type_before": undefined;
  "shared_crx_enable_desc": undefined;
  "shared_crx_enable_title": undefined;
  "shared_crx_how": undefined;
  "shared_crx_signing": undefined;
  "shared_delete_history_body": { size: string | number };
  "shared_delete_history_confirm": undefined;
  "shared_delete_history_title": undefined;
  "shared_dev_tools": undefined;
  "shared_developer": undefined;
  "shared_developer_desc": undefined;
  "shared_display": undefined;
  "shared_downloads": undefined;
  "shared_drop_desc": undefined;
  "shared_drop_to_import": undefined;
  "shared_export_all_keys": undefined;
  "shared_hide_technical_details": undefined;
  "shared_import_flow_states": undefined;
  "shared_import_keys": undefined;
  "shared_key_discovery": undefined;
  "shared_key_security": undefined;
  "shared_key_storage": undefined;
  "shared_keyboard_shortcuts": undefined;
  "shared_lock_after": undefined;
  "shared_lock_tab_away_desc": undefined;
  "shared_lock_tab_away_title": undefined;
  "shared_lookup_online_desc": undefined;
  "shared_lookup_online_title": undefined;
  "shared_master_password": undefined;
  "shared_migration_failed": undefined;
  "shared_never_cache_desc": undefined;
  "shared_never_cache_title": undefined;
  "shared_one_hour": undefined;
  "shared_open_dev_tools": undefined;
  "shared_passkey_failed": undefined;
  "shared_preset_applied": { title: string | number };
  "shared_preset_applied_history_deleted": undefined;
  "shared_preset_bundled_changed": undefined;
  "shared_preset_careful_tagline": undefined;
  "shared_preset_careful_title": undefined;
  "shared_preset_casual_tagline": undefined;
  "shared_preset_casual_title": undefined;
  "shared_preset_current": undefined;
  "shared_preset_custom": undefined;
  "shared_preset_none_selected": undefined;
  "shared_preset_paranoid_note": undefined;
  "shared_preset_paranoid_tagline": undefined;
  "shared_preset_paranoid_title": undefined;
  "shared_preset_recommended": undefined;
  "shared_saving": undefined;
  "shared_security_preset": undefined;
  "shared_show_technical_details": undefined;
  "shared_something_went_wrong": undefined;
  "shared_source_on_github": undefined;
  "shared_storage_local_desc": undefined;
  "shared_storage_local_label": undefined;
  "shared_storage_sync_desc": undefined;
  "shared_storage_sync_label": undefined;
  "shared_sync_quota_error": undefined;
  "shared_translation": undefined;
  "shared_undo": undefined;
  "shared_unlock_aria": undefined;
  "shared_unlock_failed": undefined;
  "shared_unlock_intro": undefined;
  "shared_unlock_lost_password": undefined;
  "shared_unlock_with_passkey": undefined;
  "shared_unlock_with_vault_desc": undefined;
  "shared_unlock_with_vault_title": undefined;
  "shared_unlocking": undefined;
  "shared_wrong_password": undefined;
  "workspace_add_a_contact": undefined;
  "workspace_age_message_note": undefined;
  "workspace_browse_files": undefined;
  "workspace_clear_all_files": undefined;
  "workspace_clear_input_output": undefined;
  "workspace_clear_text": undefined;
  "workspace_cleared_toast": undefined;
  "workspace_close_find": undefined;
  "workspace_compose_same_language": { language: string | number };
  "workspace_compose_translate_unavailable": undefined;
  "workspace_compose_translated": { from: string | number; to: string | number };
  "workspace_create_one": undefined;
  "workspace_crx_save_failed": undefined;
  "workspace_crx_saved": { name: string | number };
  "workspace_decrypt_with": undefined;
  "workspace_decrypting": undefined;
  "workspace_detected_key_import": undefined;
  "workspace_detected_key_in_message": { name: string | number };
  "workspace_detected_key_in_message_anon": undefined;
  "workspace_detected_key_known": { name: string | number };
  "workspace_detected_key_pasted": { name: string | number };
  "workspace_detected_key_pasted_anon": undefined;
  "workspace_detected_key_show": undefined;
  "workspace_drop_files_or_text": undefined;
  "workspace_enter_key_password": undefined;
  "workspace_enter_message_password": undefined;
  "workspace_error_crx_invalid": undefined;
  "workspace_error_crx_sign_failed": undefined;
  "workspace_error_crx_wrong_password": undefined;
  "workspace_error_decrypt_failed": undefined;
  "workspace_error_decrypt_failed_ssh": undefined;
  "workspace_error_engine_mismatch": undefined;
  "workspace_error_need_recipient_or_password": undefined;
  "workspace_error_no_signing_key": undefined;
  "workspace_error_no_signing_key_ssh": undefined;
  "workspace_error_not_signed": undefined;
  "workspace_error_read_file": undefined;
  "workspace_error_select_crx_key": undefined;
  "workspace_error_select_decryption_key": undefined;
  "workspace_error_signature_invalid": undefined;
  "workspace_error_unlock_failed": undefined;
  "workspace_error_verify_failed": undefined;
  "workspace_error_wrong_key_password": undefined;
  "workspace_find_hide_replace": undefined;
  "workspace_find_label": undefined;
  "workspace_find_replace": undefined;
  "workspace_find_show_replace": undefined;
  "workspace_go": undefined;
  "workspace_hide_password": undefined;
  "workspace_hide_technical_details": undefined;
  "workspace_history_save_failed": undefined;
  "workspace_import_one": undefined;
  "workspace_match_case": undefined;
  "workspace_message_input_aria": undefined;
  "workspace_message_password_help": undefined;
  "workspace_message_password_label": undefined;
  "workspace_message_password_title": undefined;
  "workspace_message_tools": undefined;
  "workspace_need_recipient_or_password": undefined;
  "workspace_next_match": undefined;
  "workspace_no_contacts_yet": undefined;
  "workspace_no_keys_yet": undefined;
  "workspace_no_such_language": undefined;
  "workspace_note_downloading": { what: string | number };
  "workspace_note_downloading_progress": { what: string | number; percent: string | number };
  "workspace_note_same_language": { language: string | number };
  "workspace_note_translated_from": { language: string | number };
  "workspace_note_uncertain": undefined;
  "workspace_operation_failed": undefined;
  "workspace_output_size_line": { name: string | number; size: string | number };
  "workspace_placeholder_compose": undefined;
  "workspace_placeholder_decrypt": undefined;
  "workspace_placeholder_verify": undefined;
  "workspace_previous_match": undefined;
  "workspace_private_key_clear_input": undefined;
  "workspace_private_key_ignore": undefined;
  "workspace_private_key_import_safely": undefined;
  "workspace_private_key_pasted_body": undefined;
  "workspace_private_key_pasted_title": undefined;
  "workspace_private_key_show_cleartext": undefined;
  "workspace_processing": undefined;
  "workspace_reader_locked": undefined;
  "workspace_reader_title": undefined;
  "workspace_reader_unavailable": undefined;
  "workspace_recipients_label": undefined;
  "workspace_replace": undefined;
  "workspace_replace_all": undefined;
  "workspace_replace_all_short": undefined;
  "workspace_replace_all_shortcut": { shortcut: string | number };
  "workspace_replace_with": undefined;
  "workspace_reply": undefined;
  "workspace_reply_failed": undefined;
  "workspace_reset": undefined;
  "workspace_restore_original": undefined;
  "workspace_save_file": { name: string | number };
  "workspace_search_languages": undefined;
  "workspace_select_signing_key": undefined;
  "workspace_self_excluded_age": undefined;
  "workspace_self_excluded_intro": undefined;
  "workspace_self_excluded_pgp": undefined;
  "workspace_set_password": undefined;
  "workspace_show_original": undefined;
  "workspace_show_password": undefined;
  "workspace_show_technical_details": undefined;
  "workspace_show_translation": { language: string | number };
  "workspace_sign_blocked_age": undefined;
  "workspace_sign_blocked_no_pgp_key": undefined;
  "workspace_sign_for_web_store": undefined;
  "workspace_sign_kind_crx": undefined;
  "workspace_sign_kind_pgp": undefined;
  "workspace_sign_with": undefined;
  "workspace_signature_verified": undefined;
  "workspace_status_age_encrypted": undefined;
  "workspace_status_crx_signed": { name: string | number };
  "workspace_status_crx_valid": { id: string | number };
  "workspace_status_decrypted_archive": undefined;
  "workspace_status_signer_unknown": undefined;
  "workspace_style_bold": undefined;
  "workspace_style_code": undefined;
  "workspace_style_italic": undefined;
  "workspace_style_strike": undefined;
  "workspace_text_cleared_toast": undefined;
  "workspace_text_entered_below": undefined;
  "workspace_toggle_encrypt_to_self": undefined;
  "workspace_toggle_password": undefined;
  "workspace_toggle_save_to_history": undefined;
  "workspace_toggle_zip_files": undefined;
  "workspace_translate": undefined;
  "workspace_translate_menu_heading": undefined;
  "workspace_translate_to": { language: string | number };
  "workspace_translating": undefined;
  "workspace_undo": undefined;
  "workspace_unknown_signer": undefined;
  "workspace_unlocking": undefined;
  "workspace_unverified": undefined;
  "workspace_verify_signature": undefined;
  "workspace_verifying": undefined;
  "workspace_working": undefined;
}

/** Plural base keys (the `_one` / `_other` suffix is chosen at runtime). */
export interface PluralArgs {
  "actions_history_delete_all": undefined;
  "actions_history_files": undefined;
  "actions_history_more_matches": undefined;
  "actions_keys_count": undefined;
  "app_import_added": undefined;
  "app_import_view_key": undefined;
  "app_onboarding_expiry_years": undefined;
  "app_oversized_files": { files: string | number; limit: string | number };
  "import_added_contacts": undefined;
  "import_change_keys_added": undefined;
  "import_change_keys_removed": undefined;
  "import_change_new_subkeys": undefined;
  "import_change_new_user_ids": undefined;
  "import_flagged_toast": undefined;
  "import_github_omitted_line": undefined;
  "import_github_rejected_heading": undefined;
  "import_group_help": undefined;
  "import_group_keys_chip": undefined;
  "import_group_proposal_label": undefined;
  "import_n_contacts": undefined;
  "import_retry_hours": undefined;
  "import_retry_minutes": undefined;
  "import_updated_contacts": undefined;
  "keygen_export_contacts_included": undefined;
  "keygen_export_crx_included": undefined;
  "keygen_export_still_locked": undefined;
  "keygen_export_summary_contacts": undefined;
  "keygen_export_summary_private_keys": undefined;
  "keygen_export_toast_exported": undefined;
  "keygen_export_toast_exported_unsafe": undefined;
  "keys_bulk_delete_confirm": undefined;
  "keys_bulk_delete_prompt": undefined;
  "keys_contact_keys_count": undefined;
  "keys_contacts_removed": undefined;
  "keys_count_contacts": undefined;
  "keys_count_private_keys": undefined;
  "keys_count_signing_keys": undefined;
  "keys_exported": undefined;
  "keys_exported_unsafe": undefined;
  "keys_inactive_subkeys_expired": undefined;
  "keys_inactive_subkeys_revoked": undefined;
  "keys_inactive_subkeys_unusable": undefined;
  "keys_selected_count": undefined;
  "keys_ssh_export_skipped": undefined;
  "settings_import_contacts_added": undefined;
  "settings_import_contacts_flagged": undefined;
  "settings_import_contacts_rejected": undefined;
  "settings_import_contacts_rejected_reason": { reason: string | number };
  "settings_import_contacts_updated": undefined;
  "settings_import_crx_failed": undefined;
  "settings_import_crx_rejected": undefined;
  "settings_import_crx_restored": undefined;
  "settings_import_crx_skipped": undefined;
  "settings_import_private_imported": undefined;
  "settings_import_private_skipped": undefined;
  "settings_import_private_unparseable": undefined;
  "settings_import_protect_intro": undefined;
  "settings_import_submit": undefined;
  "settings_import_unlock_intro": { encrypted: string | number };
  "shared_bundle_clipboard": undefined;
  "shared_minutes": undefined;
  "workspace_files_decrypted": { size: string | number };
  "workspace_files_encrypted": { size: string | number };
  "workspace_files_signed": undefined;
  "workspace_files_zipped_encrypted": undefined;
  "workspace_password_min_length": undefined;
  "workspace_password_too_short": undefined;
}

/** Substitution order for keys that have placeholders ($1, $2, ...). */
export const PLACEHOLDER_ORDER: Readonly<Partial<Record<string, readonly string[]>>> = {
  "actions_disabled_toast": ["name","reason"],
  "actions_history_delete_all_one": ["count"],
  "actions_history_delete_all_other": ["count"],
  "actions_history_file_with_size": ["name","size"],
  "actions_history_files_one": ["count"],
  "actions_history_files_other": ["count"],
  "actions_history_more_matches_one": ["count"],
  "actions_history_more_matches_other": ["count"],
  "actions_history_no_matches": ["query"],
  "actions_history_op_signed": ["op"],
  "actions_history_open_entry": ["title"],
  "actions_history_recipient_with_id": ["name","id"],
  "actions_history_to": ["names"],
  "actions_history_usage": ["used","budget"],
  "actions_history_when": ["date","relative"],
  "actions_keys_count_one": ["count"],
  "actions_keys_count_other": ["count"],
  "actions_keys_of_total": ["active","count"],
  "actions_language_last_used": ["label"],
  "actions_remove_recipient": ["name"],
  "actions_remove_recipient_detail": ["name","detail"],
  "actions_run_mode": ["mode"],
  "actions_translate_result_to": ["language"],
  "app_copied": ["label"],
  "app_copied_wipe": ["label","seconds"],
  "app_error_no_decryption_key_with_id": ["key_id"],
  "app_import_added_other": ["count"],
  "app_onboarding_expiry_years_one": ["count"],
  "app_onboarding_expiry_years_other": ["count"],
  "app_oversized_files_one": ["files","limit"],
  "app_oversized_files_other": ["files","limit"],
  "app_oversized_more": ["names","count"],
  "import_added_contacts_one": ["count"],
  "import_added_contacts_other": ["count"],
  "import_change_keys_added_one": ["count"],
  "import_change_keys_added_other": ["count"],
  "import_change_keys_removed_one": ["count"],
  "import_change_keys_removed_other": ["count"],
  "import_change_new_expiry": ["date"],
  "import_change_new_subkeys_one": ["count"],
  "import_change_new_subkeys_other": ["count"],
  "import_change_new_user_ids_one": ["count"],
  "import_change_new_user_ids_other": ["count"],
  "import_flagged_toast_one": ["count"],
  "import_flagged_toast_other": ["count"],
  "import_github_fetched_note": ["user"],
  "import_github_no_keys": ["username"],
  "import_github_not_found": ["username"],
  "import_github_omitted_line_one": ["count"],
  "import_github_omitted_line_other": ["count"],
  "import_github_omitted_reason": ["max","count","username"],
  "import_github_rejected_heading_one": ["count"],
  "import_github_rejected_heading_other": ["count"],
  "import_group_help_one": ["count"],
  "import_group_help_other": ["count"],
  "import_group_keys_chip_one": ["count"],
  "import_group_keys_chip_other": ["count"],
  "import_group_proposal_label_one": ["count"],
  "import_group_proposal_label_other": ["count"],
  "import_keyserver_multiple_keys": ["host"],
  "import_keyserver_not_a_key": ["host"],
  "import_keyserver_not_found_email": ["host","subject"],
  "import_keyserver_not_found_fingerprint": ["host","subject"],
  "import_keyserver_offline": ["host"],
  "import_keyserver_rate_limited": ["host"],
  "import_keyserver_server_error": ["host"],
  "import_n_contacts_one": ["count"],
  "import_n_contacts_other": ["count"],
  "import_panel_aria_with_id": ["keyid"],
  "import_paste_placeholder": ["shortcut"],
  "import_reject_expired": ["date"],
  "import_retry_hours_one": ["count"],
  "import_retry_hours_other": ["count"],
  "import_retry_minutes_one": ["count"],
  "import_retry_minutes_other": ["count"],
  "import_status_added_on": ["date"],
  "import_status_duplicate_added": ["date"],
  "import_updated_contacts_one": ["count"],
  "import_updated_contacts_other": ["count"],
  "keygen_expires_on": ["date"],
  "keygen_export_contacts_included_one": ["count"],
  "keygen_export_contacts_included_other": ["count"],
  "keygen_export_crx_included_one": ["count"],
  "keygen_export_crx_included_other": ["count"],
  "keygen_export_failed_detail": ["message"],
  "keygen_export_still_locked_one": ["count"],
  "keygen_export_still_locked_other": ["count"],
  "keygen_export_summary": ["ext","private_keys","private_block","contacts","public_block"],
  "keygen_export_summary_contacts_one": ["count"],
  "keygen_export_summary_contacts_other": ["count"],
  "keygen_export_summary_private_keys_one": ["count"],
  "keygen_export_summary_private_keys_other": ["count"],
  "keygen_export_toast_exported_one": ["count"],
  "keygen_export_toast_exported_other": ["count"],
  "keygen_export_toast_exported_unsafe_one": ["count"],
  "keygen_export_toast_exported_unsafe_other": ["count"],
  "keys_banner_expired_on": ["date"],
  "keys_banner_expired_title": ["when"],
  "keys_bits": ["bits"],
  "keys_bulk_delete_confirm_one": ["count"],
  "keys_bulk_delete_confirm_other": ["count"],
  "keys_bulk_delete_prompt_one": ["count"],
  "keys_bulk_delete_prompt_other": ["count"],
  "keys_contact_expired": ["date"],
  "keys_contact_expired_title": ["date"],
  "keys_contact_expires": ["date"],
  "keys_contact_keys_count_one": ["count"],
  "keys_contact_keys_count_other": ["count"],
  "keys_contact_keys_partial": ["active","total"],
  "keys_contact_keys_partial_title": ["active","total"],
  "keys_contacts_heading_count": ["count"],
  "keys_contacts_removed_other": ["count"],
  "keys_count_contacts_one": ["count"],
  "keys_count_contacts_other": ["count"],
  "keys_count_private_keys_one": ["count"],
  "keys_count_private_keys_other": ["count"],
  "keys_count_signing_keys_one": ["count"],
  "keys_count_signing_keys_other": ["count"],
  "keys_details_aria": ["name"],
  "keys_expires_value": ["date","when"],
  "keys_exported_one": ["count"],
  "keys_exported_other": ["count"],
  "keys_exported_unsafe_one": ["count"],
  "keys_exported_unsafe_other": ["count"],
  "keys_inactive_subkeys_expired_one": ["count"],
  "keys_inactive_subkeys_expired_other": ["count"],
  "keys_inactive_subkeys_revoked_one": ["count"],
  "keys_inactive_subkeys_revoked_other": ["count"],
  "keys_inactive_subkeys_unusable_one": ["count"],
  "keys_inactive_subkeys_unusable_other": ["count"],
  "keys_no_contacts_match": ["query"],
  "keys_rename_hint": ["identity"],
  "keys_revoked_reason": ["reason"],
  "keys_row_created": ["date"],
  "keys_row_expired": ["date"],
  "keys_row_expires": ["date"],
  "keys_selected_count_one": ["count"],
  "keys_selected_count_other": ["count"],
  "keys_size_bytes": ["size"],
  "keys_size_kb": ["size"],
  "keys_size_mb": ["size"],
  "keys_source_github": ["user"],
  "keys_source_keyserver": ["user"],
  "keys_ssh_export_skipped_one": ["count"],
  "keys_ssh_export_skipped_other": ["count"],
  "keys_subkeys_truncated": ["count"],
  "settings_crx_info_get_body": ["crx","load_unpacked"],
  "settings_crx_info_ladder_ci": ["term"],
  "settings_crx_info_ladder_hardware": ["term"],
  "settings_crx_info_ladder_vault": ["term"],
  "settings_crx_info_not_pgp_body": ["crx"],
  "settings_crx_info_step_2": ["public","path"],
  "settings_crx_info_step_3": ["zip","save","crx"],
  "settings_crx_info_step_4": ["crx"],
  "settings_import_contacts_added_one": ["count"],
  "settings_import_contacts_added_other": ["count"],
  "settings_import_contacts_flagged_one": ["count"],
  "settings_import_contacts_flagged_other": ["count"],
  "settings_import_contacts_rejected_one": ["count"],
  "settings_import_contacts_rejected_other": ["count"],
  "settings_import_contacts_rejected_reason_one": ["count","reason"],
  "settings_import_contacts_rejected_reason_other": ["count","reason"],
  "settings_import_contacts_updated_one": ["count"],
  "settings_import_contacts_updated_other": ["count"],
  "settings_import_crx_failed_one": ["count"],
  "settings_import_crx_failed_other": ["count"],
  "settings_import_crx_failure_detail": ["name","error"],
  "settings_import_crx_rejected_one": ["count"],
  "settings_import_crx_rejected_other": ["count"],
  "settings_import_crx_restored_one": ["count"],
  "settings_import_crx_restored_other": ["count"],
  "settings_import_crx_skipped_one": ["count"],
  "settings_import_crx_skipped_other": ["count"],
  "settings_import_failed_named": ["name","error"],
  "settings_import_private_imported_one": ["count"],
  "settings_import_private_imported_other": ["count"],
  "settings_import_private_skipped_one": ["count"],
  "settings_import_private_skipped_other": ["count"],
  "settings_import_private_unparseable_one": ["count"],
  "settings_import_private_unparseable_other": ["count"],
  "settings_import_protect_intro_one": ["count"],
  "settings_import_protect_intro_other": ["count"],
  "settings_import_submit_one": ["count"],
  "settings_import_submit_other": ["count"],
  "settings_import_unlock_intro_one": ["encrypted","count"],
  "settings_import_unlock_intro_other": ["encrypted","count"],
  "settings_preset_confirm_history": ["size"],
  "settings_preset_confirm_replace": ["preset"],
  "settings_preset_custom_notice": ["custom"],
  "settings_shortcuts_global_note": ["url"],
  "settings_shortcuts_open_in_mode": ["mode"],
  "settings_shortcuts_switch_mode": ["mode"],
  "settings_translation_pack_pair": ["from","to"],
  "settings_translation_pack_progress": ["percent"],
  "settings_translation_packs_desc": ["size"],
  "shared_bundle_auto_lock": ["duration"],
  "shared_bundle_auto_lock_tabs": ["duration"],
  "shared_bundle_clipboard_one": ["count"],
  "shared_bundle_clipboard_other": ["count"],
  "shared_confirm_type_aria": ["text"],
  "shared_delete_history_body": ["size"],
  "shared_minutes_one": ["count"],
  "shared_minutes_other": ["count"],
  "shared_preset_applied": ["title"],
  "workspace_compose_same_language": ["language"],
  "workspace_compose_translated": ["from","to"],
  "workspace_crx_saved": ["name"],
  "workspace_detected_key_in_message": ["name"],
  "workspace_detected_key_known": ["name"],
  "workspace_detected_key_pasted": ["name"],
  "workspace_files_decrypted_one": ["count","size"],
  "workspace_files_decrypted_other": ["count","size"],
  "workspace_files_encrypted_one": ["count","size"],
  "workspace_files_encrypted_other": ["count","size"],
  "workspace_files_signed_one": ["count"],
  "workspace_files_signed_other": ["count"],
  "workspace_files_zipped_encrypted_one": ["count"],
  "workspace_files_zipped_encrypted_other": ["count"],
  "workspace_note_downloading": ["what"],
  "workspace_note_downloading_progress": ["what","percent"],
  "workspace_note_same_language": ["language"],
  "workspace_note_translated_from": ["language"],
  "workspace_output_size_line": ["name","size"],
  "workspace_password_min_length_one": ["count"],
  "workspace_password_min_length_other": ["count"],
  "workspace_password_too_short_one": ["count"],
  "workspace_password_too_short_other": ["count"],
  "workspace_replace_all_shortcut": ["shortcut"],
  "workspace_save_file": ["name"],
  "workspace_show_translation": ["language"],
  "workspace_status_crx_signed": ["name"],
  "workspace_status_crx_valid": ["id"],
  "workspace_translate_to": ["language"],
};
