#!/usr/bin/env bash
# Regenerate e2e/keys.ts: a spread of real OpenPGP keys + cleartext-signed
# messages, produced with a throwaway gpg homedir. Run from apps/pgp:
#   ./e2e/gen-keys.sh
# Requires gpg (2.4+) and python3.
set -euo pipefail
cd "$(dirname "$0")/.."

export GNUPGHOME="$(mktemp -d)"
trap 'rm -rf "$GNUPGHOME"' EXIT
MSG="The quick brown fox jumps over the lazy dog."
q(){ gpg --batch --pinentry-mode loopback --passphrase '' \
       --quick-generate-key "$1" "$2" "$3" 1y >/dev/null 2>&1; }

q "Alice Example <alice@example.com>" default default
q "Bob NoEmail" default default
q "Carol Work (work laptop) <carol@example.com>" default default
q "Dave RSA <dave@example.com>" rsa2048 default
# quick-gen makes the RSA primary sign-only; add an encryption subkey.
DAVE=$(gpg --list-keys --with-colons dave@example.com | awk -F: '/^fpr:/{print $10;exit}')
gpg --batch --pinentry-mode loopback --passphrase '' \
    --quick-add-key "$DAVE" rsa2048 encr 1y >/dev/null 2>&1
# Sign-only keys (no encryption subkey), with and without an email.
q "Erin SignOnly <erin@example.com>" ed25519 sign
q "Frank SignOnlyNoEmail" ed25519 sign

python3 - "$MSG" << 'PYEOF'
import subprocess, json, sys
msg = sys.argv[1]
out = subprocess.run(["gpg","--list-keys","--with-colons"],
                     capture_output=True, text=True).stdout
keys=[]; cur=None
for line in out.splitlines():
    f=line.split(":")
    if f[0]=="pub": cur={"fpr":None,"uid":None}
    elif f[0]=="fpr" and cur and cur["fpr"] is None: cur["fpr"]=f[9]
    elif f[0]=="uid" and cur and cur["uid"] is None:
        cur["uid"]=f[9]; keys.append(cur); cur=None

# slug -> (label, email, encryptCapable, description)
meta = {
 "Alice Example <alice@example.com>":              ("standard","Alice Example","alice@example.com",True,"name + email, encryption-capable"),
 "Bob NoEmail":                                    ("noEmail","Bob NoEmail","",True,"user ID with NO email, encryption-capable"),
 "Carol Work (work laptop) <carol@example.com>":   ("comment","Carol Work (work laptop)","carol@example.com",True,"name + comment + email"),
 "Dave RSA <dave@example.com>":                    ("rsa","Dave RSA","dave@example.com",True,"RSA-2048 key with encryption subkey"),
 "Erin SignOnly <erin@example.com>":               ("signOnly","Erin SignOnly","erin@example.com",False,"sign-only key (no encryption subkey)"),
 "Frank SignOnlyNoEmail":                          ("signOnlyNoEmail","Frank SignOnlyNoEmail","",False,"sign-only key with NO email"),
}
order=["standard","noEmail","comment","rsa","signOnly","signOnlyNoEmail"]
rows={}
for k in keys:
    m=meta.get(k["uid"])
    if not m: continue
    slug,label,email,enc,desc=m
    pub=subprocess.run(["gpg","--armor","--export",k["fpr"]],capture_output=True,text=True).stdout
    signed=subprocess.run(["gpg","--batch","--pinentry-mode","loopback","--passphrase","",
                           "--clearsign","-u",k["fpr"]],input=msg,capture_output=True,text=True).stdout
    rows[slug]=dict(slug=slug,label=label,description=desc,uid=k["uid"],name=label,
                    email=email,encryptCapable=enc,fingerprint=k["fpr"],
                    publicKey=pub,signedMessage=signed)

L=['// AUTO-GENERATED by e2e/gen-keys.sh -- do not edit by hand.',
   '// Real OpenPGP keys + cleartext-signed messages spanning a range of',
   '// user-ID shapes and capabilities.','',
   'export interface TestKey {','  slug: string;','  /** Human label / display name. */','  label: string;',
   '  description: string;','  /** Primary user ID as stored in the cert. */','  uid: string;',
   '  name: string;','  /** Email in the uid, or "" when the key has none. */','  email: string;',
   '  /** Whether the key can be encrypted to (has an encryption subkey). */','  encryptCapable: boolean;',
   '  fingerprint: string;','  publicKey: string;',
   '  /** Cleartext-signed copy of MESSAGE, made by this key. */','  signedMessage: string;','}','',
   f'export const MESSAGE = {json.dumps(msg)};','','export const TEST_KEYS: TestKey[] = [']
for slug in order:
    d=rows[slug]
    L.append('  {')
    for key in ["slug","label","description","uid","name","email"]:
        L.append(f'    {key}: {json.dumps(d[key])},')
    L.append(f'    encryptCapable: {"true" if d["encryptCapable"] else "false"},')
    L.append(f'    fingerprint: {json.dumps(d["fingerprint"])},')
    L.append(f'    publicKey: {json.dumps(d["publicKey"])},')
    L.append(f'    signedMessage: {json.dumps(d["signedMessage"])},')
    L.append('  },')
L+=[ '];','',
     '/** Look up a fixture by slug (throws if missing) -- avoids non-null `!`. */',
     'export function keyBySlug(slug: string): TestKey {',
     '  const key = TEST_KEYS.find((k) => k.slug === slug);',
     '  if (!key) throw new Error(`No test key with slug "${slug}"`);',
     '  return key;','}','']
open("e2e/keys.ts","w").write("\n".join(L))
print("wrote e2e/keys.ts with", len(rows), "keys")
PYEOF
