// AUTO-GENERATED by e2e/gen-keys.sh -- do not edit by hand.
// Real OpenPGP keys + cleartext-signed messages spanning a range of
// user-ID shapes and capabilities.

export interface TestKey {
  slug: string;
  /** Human label / display name. */
  label: string;
  description: string;
  /** Primary user ID as stored in the cert. */
  uid: string;
  name: string;
  /** Email in the uid, or "" when the key has none. */
  email: string;
  /** Whether the key can be encrypted to (has an encryption subkey). */
  encryptCapable: boolean;
  fingerprint: string;
  publicKey: string;
  /** Cleartext-signed copy of MESSAGE, made by this key. */
  signedMessage: string;
}

export const MESSAGE = "The quick brown fox jumps over the lazy dog.";

export const TEST_KEYS: TestKey[] = [
  {
    slug: "standard",
    label: "Alice Example",
    description: "name + email, encryption-capable",
    uid: "Alice Example <alice@example.com>",
    name: "Alice Example",
    email: "alice@example.com",
    encryptCapable: true,
    fingerprint: "1D2DFAC2C18051E9C11037A6E3AA99801E250E69",
    publicKey:
      "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmDMEakqJ5xYJKwYBBAHaRw8BAQdAIjJG0X0Nw0cenGiII9fMdGY9kMeLKwW6JaM4\neCrOd2q0IUFsaWNlIEV4YW1wbGUgPGFsaWNlQGV4YW1wbGUuY29tPoiZBBMWCgBB\nFiEEHS36wsGAUenBEDem46qZgB4lDmkFAmpKiecCGwMFCQHhM4AFCwkIBwICIgIG\nFQoJCAsCBBYCAwECHgcCF4AACgkQ46qZgB4lDmlWvwEA8xgDlzENwBEN3kMKF3F+\nRCdi2FPTe8X3cTKLDnsIZPYA/1KuhEsTZ8UL/OoJKF6L4V+tzgSH/Ngg8Q0BYwBJ\nfyYCuDgEakqJ5xIKKwYBBAGXVQEFAQEHQJW6bXIpCwUFAw65OmeZG+v3yR5DiOC1\nqzqigc9FmD9hAwEIB4h4BBgWCgAgFiEEHS36wsGAUenBEDem46qZgB4lDmkFAmpK\niecCGwwACgkQ46qZgB4lDmlkAwEAyBcizu5PS23a2FkT7TVB1go1RPjIJ3bKF5mv\nhoruwtIBAI7hKSS0l1ufhI2y0NPIldDDDtcFCd9si6ijrvpxiz0H\n=+RBp\n-----END PGP PUBLIC KEY BLOCK-----\n",
    signedMessage:
      "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA512\n\nThe quick brown fox jumps over the lazy dog.\n-----BEGIN PGP SIGNATURE-----\n\niHUEARYKAB0WIQQdLfrCwYBR6cEQN6bjqpmAHiUOaQUCakqJ6AAKCRDjqpmAHiUO\nad24AP9ulYokVwSSUAknOIpquaBGKaemRHlPcZBlFj1G8u96CQEAggXCqsfiDg0+\nJe5Su/hgiFYRFR6NxyybB/9vRoF0cw4=\n=sFNz\n-----END PGP SIGNATURE-----\n",
  },
  {
    slug: "noEmail",
    label: "Bob NoEmail",
    description: "user ID with NO email, encryption-capable",
    uid: "Bob NoEmail",
    name: "Bob NoEmail",
    email: "",
    encryptCapable: true,
    fingerprint: "D0B5D719A07350EF321E04946E98DB9F375D81CD",
    publicKey:
      "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmDMEakqJ5xYJKwYBBAHaRw8BAQdAyp0+m7V5quBtmhfL3hRffL1cE3nzv3JNwAIX\nDEujETO0C0JvYiBOb0VtYWlsiJkEExYKAEEWIQTQtdcZoHNQ7zIeBJRumNufN12B\nzQUCakqJ5wIbAwUJAeEzgAULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRBu\nmNufN12BzVPfAQCJWh6OsPQfVCffAW6vP9o6pBPpI6CRwT0xc4XPIunhLwD+NyBS\n+kyqSscRHAr9b0KBPrsl4LSJ++X2ZBgxef9BqwK4OARqSonnEgorBgEEAZdVAQUB\nAQdAe+1flswqMop7JL4baSmsiJ5PZLxMLI072NUENudpUVEDAQgHiHgEGBYKACAW\nIQTQtdcZoHNQ7zIeBJRumNufN12BzQUCakqJ5wIbDAAKCRBumNufN12BzbfbAP9k\nTgWvx+96gj09xsOd8TElDRkWX6JuVrfJxyXWPGMv7wD/W6192jG1TIDOl91JpyVF\nt6KhRl0Y06chGY66IXi+yQw=\n=GZ5D\n-----END PGP PUBLIC KEY BLOCK-----\n",
    signedMessage:
      "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA512\n\nThe quick brown fox jumps over the lazy dog.\n-----BEGIN PGP SIGNATURE-----\n\niHUEARYKAB0WIQTQtdcZoHNQ7zIeBJRumNufN12BzQUCakqJ6AAKCRBumNufN12B\nzechAQDHs6ULvdLp4eyXbZhka7pR4BlrRKAjsxVqQ5beqOyafwD+MgQvdBsjfw+M\nBTkH/3ZjmeRVYeyxKOh8JwizF6/fCQU=\n=q/D7\n-----END PGP SIGNATURE-----\n",
  },
  {
    slug: "comment",
    label: "Carol Work (work laptop)",
    description: "name + comment + email",
    uid: "Carol Work (work laptop) <carol@example.com>",
    name: "Carol Work (work laptop)",
    email: "carol@example.com",
    encryptCapable: true,
    fingerprint: "9DF50FBF0893DECB7265ACF88378AEEFAF1BF72A",
    publicKey:
      "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmDMEakqJ5xYJKwYBBAHaRw8BAQdAoNFtgpKTYcqsPm94AGMzpv0ACtYeqzskd6VK\nXS6aX4O0LENhcm9sIFdvcmsgKHdvcmsgbGFwdG9wKSA8Y2Fyb2xAZXhhbXBsZS5j\nb20+iJkEExYKAEEWIQSd9Q+/CJPey3JlrPiDeK7vrxv3KgUCakqJ5wIbAwUJAeEz\ngAULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRCDeK7vrxv3KiKLAP4soW7s\n/NAc5F7xzHuubtVC1ffR8CobKejTzhlSvh9FVQEA5EsELqxmgLAhC3U/RaBVzmi6\nkMjv3UO8fo+CC+XNUA+4OARqSonnEgorBgEEAZdVAQUBAQdA9pRljPUG5kfcMMxo\noLE773yBzrH/lOY0jwOww8+mRxIDAQgHiHgEGBYKACAWIQSd9Q+/CJPey3JlrPiD\neK7vrxv3KgUCakqJ5wIbDAAKCRCDeK7vrxv3KnvlAP0Vfc7bwdYGVQB83uBNoW5h\nxQKlpXbRqi9SJFCDB9BFjAEAgfRwMkExPtu17kISSO/ksRZx53pe9sZc/EEzrYOc\nDQU=\n=vPiK\n-----END PGP PUBLIC KEY BLOCK-----\n",
    signedMessage:
      "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA512\n\nThe quick brown fox jumps over the lazy dog.\n-----BEGIN PGP SIGNATURE-----\n\niHUEARYKAB0WIQSd9Q+/CJPey3JlrPiDeK7vrxv3KgUCakqJ6AAKCRCDeK7vrxv3\nKipfAQCHlVvHZ8ZVXv2qYaWvLw96kSbRC5qLujVtQlRDXuEzmAD/Ru2G/FzKaPnF\nyJ+55WWlu9GdwODI9HUtQ+18IMa9JwM=\n=E7kn\n-----END PGP SIGNATURE-----\n",
  },
  {
    slug: "rsa",
    label: "Dave RSA",
    description: "RSA-2048 key with encryption subkey",
    uid: "Dave RSA <dave@example.com>",
    name: "Dave RSA",
    email: "dave@example.com",
    encryptCapable: true,
    fingerprint: "8CAAB0E3494A5B42CCC544EB99B80ED0724FE19F",
    publicKey:
      "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQENBGpKiecBCAC5oRTqhzj3eA1E0gw6ABEO8hmNEUvB2JwyXf8F3EJTr/6GAYnt\n+QcsdyBCMOjNMKtXODODBiB24p/8XxTUT9LYWPKCWPcTQ43m4DfCHjVwjOsHuVnI\nH5DjdsFsEYGXl9RO0M+x4Qr2YTCqpy2JCgFCk7d/09nwzvzYUeqh3s/ejKVCyP+w\n7qPbhwukPhOq++pAe5tIRHe36RAjzjI7l/UdkmXI00ckrH1pMmTXCbsoxUrS1hUK\nO6c5W9+xA2omYz3UXxa01Gtan2KqkSYn/XWld9tBOWO6iYZuUBPbhFdoqFArHbFR\nwsYQr49opiSXKfA+2bZPtVCyPF7kL4Ywt3wxABEBAAG0G0RhdmUgUlNBIDxkYXZl\nQGV4YW1wbGUuY29tPokBVwQTAQgAQRYhBIyqsONJSltCzMVE65m4DtByT+GfBQJq\nSonnAhsDBQkB4TOABQsJCAcCAiICBhUKCQgLAgQWAgMBAh4HAheAAAoJEJm4DtBy\nT+Gfuz4IAIuq9wVaEy1fHN+cOgFrNo1t77CQyQfGaV0FV8Ct3MQ1LzfHq2agqnEn\nHZv4n8KGuc5je7V4KMsuIfatYOSkHzta7Vk6es+rZWg2eZ7PHo6LFH9ukIKV4Pte\n4PIsvxgm3FR1EjqNyewe73mqkSXwElVyGoKMeOvqU0PH8vgl3VLCF3G8YEZ1ttkE\nAC4yEAWYpYPq/96U+n0rXxM74LAiS3p96l+ukXeCpsFDqULXz3JEuSthLHhqJzAs\nZ3UVutcX6ZZHkAd7XW/8Tr4ifnjHNz7TQgxN4rLgZS3N0DQZbbOtVuBkbE5Q9dAW\nYlLHJbLQRnqoEEnxWcEXcIfR6//xoRy5AQ0EakqJ5wEIAMH8uvQZ7h7hVPdiAynY\nU6zR8fm4GMtd3Io58FkMU6TmldDeH8xSPRfvwBsrquqxb97Uq4JAylr6Wq47SGfk\nTh6jpPLUljWzdyEx8XEBvIdNFlPFt3CpYaHje5u6gUv9vTt8g7tiFWTo3rT5CN2G\nKqCLQlzrKYXpgEEIRwCHhdv1CcrbssQQ0BHw3KHGAEhXX21ICFTt00T32SV/aQoO\nkc11ppEiR1JSZNTpWpe1D0rltDeHFwt13jRaodY8dCgetztlat4Wkx7lXkWCD14y\nEiMqQcZqJKYzIyjjxLTAuHbCTY+2giVhWrxMAJ+EHx5kleT2HxVh2xwEsTBOmKOP\nY6kAEQEAAYkBPAQYAQgAJhYhBIyqsONJSltCzMVE65m4DtByT+GfBQJqSonnAhsM\nBQkB4TOAAAoJEJm4DtByT+Gf0A8IALHlKjNn/TPVdkv20S1AELGwLrjid1OI9YZD\nmeiqpqWsuRP7g6t1QPjzmaZ+TeUlBvIFXz3bXjaXXX6F9xO3WKlrsnJXCmwJgfKS\n3LhyULCRfsTqSFFgJHD7lFzVcYlgGn0xfu5QPokwUVfz2N1S9zBl9RXY5uvwXWMn\nilSH9GgLipxeNZUId1pbCIG0cL6Ac30chAqzEGJfHn7FNmXlL/GKPn1gNS4ZwI/C\nJ2PM7EjmwiSvXjmGv47yoFo3Ekt03SCehdiuYewtX+iDxh0bCgxwYsyOMgjPpSWE\nCW6j9qA9hLSwxiSK9/zdOGJvztgXuWrlwK3CYXLqd9Zb+n4IJw8=\n=b/hz\n-----END PGP PUBLIC KEY BLOCK-----\n",
    signedMessage:
      "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA256\n\nThe quick brown fox jumps over the lazy dog.\n-----BEGIN PGP SIGNATURE-----\n\niQEzBAEBCAAdFiEEjKqw40lKW0LMxUTrmbgO0HJP4Z8FAmpKiegACgkQmbgO0HJP\n4Z/jfggAh35IVwV1qPnrn7U5Ztpd3galAJyaj24LBD2jH1xlR6eE2ucVp7Eac/Ks\nz12JipAkECR3dXcHSVUqCsufzDAT0cm9rHR8RrPpVKZONZybShuxm1YLlrlk8Ngb\nWJl4fE2qBn1yLXSgNlzBHt8Fvyc8ioe4C0JL8Ku9suyYls8xgZuHQN6gz1OcqEsy\nWaQS7nPsbzuYR3AZXEx4cBBBbXWyVCPJD1c2b1E61Bj0leE08mMGmsV4+D0KODfs\nfb75z1OUeFaUVf4mOIsgztmJ0qSk8IXPqT6XQ2or/3BP2Q2w4TDW1s1hGSEzGpQJ\nKlKN0KMyHiG34vfkL+if47P+V4v7ow==\n=XV99\n-----END PGP SIGNATURE-----\n",
  },
  {
    slug: "signOnly",
    label: "Erin SignOnly",
    description: "sign-only key (no encryption subkey)",
    uid: "Erin SignOnly <erin@example.com>",
    name: "Erin SignOnly",
    email: "erin@example.com",
    encryptCapable: false,
    fingerprint: "D71CB7A24DBFA536BFC0245DF78B1E203269B44A",
    publicKey:
      "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmDMEakqJ6BYJKwYBBAHaRw8BAQdA6MeClbdh983XdMRtnBNnyPFC9lzX7JZ3Ftqw\n+F7Wmu20IEVyaW4gU2lnbk9ubHkgPGVyaW5AZXhhbXBsZS5jb20+iJkEExYKAEEW\nIQTXHLeiTb+lNr/AJF33ix4gMmm0SgUCakqJ6AIbAwUJAeEzgAULCQgHAgIiAgYV\nCgkICwIEFgIDAQIeBwIXgAAKCRD3ix4gMmm0SjGdAP49Ew+nys7hcz+WDFmnya86\neQStOOE/mxT3UwZRxE+9dAEA2Pj8cYWW0/kUFjh0yQPdooVGDyVTxHiY4duDxxVY\nvAE=\n=oBdm\n-----END PGP PUBLIC KEY BLOCK-----\n",
    signedMessage:
      "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA512\n\nThe quick brown fox jumps over the lazy dog.\n-----BEGIN PGP SIGNATURE-----\n\niHUEARYKAB0WIQTXHLeiTb+lNr/AJF33ix4gMmm0SgUCakqJ6AAKCRD3ix4gMmm0\nSsfzAP99Af/+SlDhhnKOC/Dp0n5Td0q2dwUnL4rsIugh6jI1MAEAhDDhNvE2MUBM\nrk2xPXjmqed0JrwbJoW6gDSqGJWnwwY=\n=RCq7\n-----END PGP SIGNATURE-----\n",
  },
  {
    slug: "signOnlyNoEmail",
    label: "Frank SignOnlyNoEmail",
    description: "sign-only key with NO email",
    uid: "Frank SignOnlyNoEmail",
    name: "Frank SignOnlyNoEmail",
    email: "",
    encryptCapable: false,
    fingerprint: "FC78DA4DDC926F4784C66960191B269039F747A8",
    publicKey:
      "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmDMEakqJ6BYJKwYBBAHaRw8BAQdAsXAqbif8Mf40cLEcxZ7XyOPb0LlR1JPvQ6Iq\nWVWOrnK0FUZyYW5rIFNpZ25Pbmx5Tm9FbWFpbIiZBBMWCgBBFiEE/HjaTdySb0eE\nxmlgGRsmkDn3R6gFAmpKiegCGwMFCQHhM4AFCwkIBwICIgIGFQoJCAsCBBYCAwEC\nHgcCF4AACgkQGRsmkDn3R6idSQEAsSFx+Aew0iOC/GPGT4DPpqx/AaW5jTHsDkHK\nHYV4NM8BAJp0CKHd7hTkP7DLpxoTD1gYsEHcqq4WWc1lqCNDN20O\n=QZGS\n-----END PGP PUBLIC KEY BLOCK-----\n",
    signedMessage:
      "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA512\n\nThe quick brown fox jumps over the lazy dog.\n-----BEGIN PGP SIGNATURE-----\n\niHUEARYKAB0WIQT8eNpN3JJvR4TGaWAZGyaQOfdHqAUCakqJ6AAKCRAZGyaQOfdH\nqJO4AQDV7/y3oXg3Gf/oTO0yWpSzdlkOQgppfMnqZKj1A7UQJAEA6sqZHnkLFDlm\nlVhbvmRaghCOM4VW6GIUbvNC5Kzmlw4=\n=syUL\n-----END PGP SIGNATURE-----\n",
  },
];

/** Look up a fixture by slug (throws if missing) -- avoids non-null `!`. */
export function keyBySlug(slug: string): TestKey {
  const key = TEST_KEYS.find((k) => k.slug === slug);
  if (!key) throw new Error(`No test key with slug "${slug}"`);
  return key;
}
